List<String> diseases = [
  "COVID-19",
  "Influenza",
  "HIV/AIDS",
  "Malaria",
  "Tuberculosis",
  "Cholera",
  "Dengue fever",
  "Ebola virus disease",
  "Hepatitis B and C",
  "Measles",
  "Pneumonia",
  "Polio",
  "SARS (Severe Acute Respiratory Syndrome)",
  "Smallpox",
  "Typhoid fever",
  "Yellow fever",
  "Zika virus",
  "West Nile virus",
  "Lyme disease",
  "Rabies",
  "Meningitis",
  "Gonorrhea",
  "Syphilis",
  "MRSA (Methicillin-resistant Staphylococcus aureus)",
  "Norovirus",
  "E. coli infection",
  "Salmonella infection",
  "Listeria infection",
  "Avian influenza (Bird flu)",
  "Swine flu",
  "Middle East respiratory syndrome (MERS)",
  "SARS-CoV-2 variants (Delta, Omicron, etc.)",
  "Leptospirosis"
];
